(load "harn")
=(h (harn.create))

(print)
(print "**** Birth Attributes ****")
(print (harn.attr-name :sp) (harn.species-name (harn.get-attr h :sp)))
(print (harn.attr-name :sx) (harn.sex-name (harn.get-attr h :sx)))
(do =(bd (harn.get-attr h :bd)) (print (harn.attr-name :bd) (harn.month-name (fst bd)) (snd bd)))
(print (harn.attr-name :ss) (harn.sunsign-name (harn.get-attr h :ss)))
(print (harn.attr-name :fr) (harn.frame-name (harn.get-attr h :fr)))

(print)
(print "**** Physical Attributes ****")
(map
  @({} {print (harn.attr-name &1) (harn.get-attr h &1)})
  {:ht :owt :cml :str :sta :dex :agl :spd :eye :hrg :smt :tch :voi :int :aur :wil :mor :pty :dty}
)
; :end 
(print (harn.attr-name :end) (harn.end h))

(print)
(print "**** Automatic Skills ****")
=(auto-skills (map
  @({} {print (harn.skill.name &1) (harn.get-oml h &1)})
  (filter
    @({} {harn.skill.auto &1})
    (hash-keys harn.skills)
  )
))
